require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BasePlatform' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true
  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'
  pod 'Firebase/Analytics'

end


